insert into address(zipCode, street, number,  state,  city,  country) values ('9999','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');
insert into address(zipCode, street, number,  state,  city,  country) values ('1234','street','number','state','city','country');



insert into user(name,lastName,age,addressId) values ('aaaaaa','lastname',1 , 1 );
insert into user(name,lastName,age,addressId) values ('AAAAAA','aaaaaal' ,2 , 2 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,3 , 3 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,4 , 4 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,5 , 5 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,6 , 6 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,7 , 7 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,8 , 8 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,9 , 9 );
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,10, 10);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,11, 11);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,12, 12);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,13, 13);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,14, 14);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,15, 15);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,16, 16);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,17, 17);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,18, 18);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,19, 19);
insert into user(name,lastName,age,addressId) values ('aaaaaa','aaaaaal' ,20, 20);
insert into user(name,lastName,age,addressId) values ('iiiiii','aaaaaal' ,21, 21);
insert into user(name,lastName,age,addressId) values ('iiiiii','aaaaaal' ,22, 22);
insert into user(name,lastName,age,addressId) values ('jjjjjj','aaaaaal' ,23, 23);
insert into user(name,lastName,age,addressId) values ('jjjjjj','aaaaaal' ,24, 24);
insert into user(name,lastName,age,addressId) values ('kkkkkk','aaaaaal' ,25, 25);
insert into user(name,lastName,age,addressId) values ('kkkkkk','aaaaaal' ,26, 26);
insert into user(name,lastName,age,addressId) values ('llllll','aaaaaal' ,27, 27);
insert into user(name,lastName,age,addressId) values ('llllll','aaaaaal' ,28, 28);
insert into user(name,lastName,age,addressId) values ('mmmmmm','aaaaaal' ,29, 29);
insert into user(name,lastName,age,addressId) values ('mmmmmm','aaaaaal' ,30, 30);
insert into user(name,lastName,age,addressId) values ('nnnnnn','aaaaaal' ,31, 31);
insert into user(name,lastName,age,addressId) values ('nnnnnn','aaaaaal' ,32, 32);
insert into user(name,lastName,age,addressId) values ('oooooo','aaaaaal' ,33, 33);
insert into user(name,lastName,age,addressId) values ('oooooo','aaaaaal' ,34, 34);
insert into user(name,lastName,age,addressId) values ('pppppp','aaaaaal' ,35, 35);
insert into user(name,lastName,age,addressId) values ('pppppp','aaaaaal' ,36, 36);
insert into user(name,lastName,age,addressId) values ('qqqqqq','aaaaaal' ,37, 37);
insert into user(name,lastName,age,addressId) values ('rrrrrr','aaaaaal' ,38, 38);
insert into user(name,lastName,age,addressId) values ('rrrrrr','aaaaaal' ,39, 39);
insert into user(name,lastName,age,addressId) values ('zzzzzz','zzzzzzl' ,40, 40);

